### ISSUE TITLE
style fixes

### ISSUE THREAD

**Issue by fetsorn** [Graviton-One/graviton-treasury#1]
Didn’t find much in terms of errors but here’s what can be done about style

change tresury treAsury
Remove whitespace after (
https://github.com/Graviton-One/graviton-treasury/blob/6f12179d23c861d68495b896d6cf7f2fde720b4d/storage.sol#L84

Remove whitespace after uint
https://github.com/Graviton-One/graviton-treasury/blob/6f12179d23c861d68495b896d6cf7f2fde720b4d/storage.sol#L29

Remove whitespace after (
https://github.com/Graviton-One/graviton-treasury/blob/6f12179d23c861d68495b896d6cf7f2fde720b4d/storage.sol#L84

Remove whitespace after =
https://github.com/Graviton-One/graviton-treasury/blob/6f12179d23c861d68495b896d6cf7f2fde720b4d/storage.sol#L102

**Comment by BadConfig** [comment]
Fine)
