### ISSUE TITLE
[Extractor Server API] Route constraints

### ISSUE THREAD

**Issue by sham789** [Graviton-One/graviton-treasury#2]
An extractor is considered valid only if the one has:
- "/extract" route with type "GET"
- "/info" route with type "GET"
- "/aggregate" route with type "POST"

These routes are vital due to a fact that `gravity-core` node is tied to this only specific interface.
Please, rename to "/extract".

https://github.com/Graviton-One/graviton-treasury/blob/6f12179d23c861d68495b896d6cf7f2fde720b4d/gravity_extractor/api_server/src/main.rs#L9

**Comment by BadConfig** [comment]
Got it
