### ISSUE TITLE
[Ethereum LU] EthScan improvements

### ISSUE THREAD

**Issue by sham789** [Graviton-One/graviton-treasury#4]
No input params for function.
EthScan API supports different params and the client is worth supporting them too.

https://github.com/Graviton-One/graviton-treasury/blob/6f12179d23c861d68495b896d6cf7f2fde720b4d/gravity_extractor/etherium_lu/src/lib.rs#L104

Hardcoded Rinkeby. We can try using ENV variables.

https://github.com/Graviton-One/graviton-treasury/blob/6f12179d23c861d68495b896d6cf7f2fde720b4d/gravity_extractor/etherium_lu/src/lib.rs#L109

https://github.com/Graviton-One/graviton-treasury/blob/6f12179d23c861d68495b896d6cf7f2fde720b4d/gravity_extractor/etherium_lu/src/lib.rs#L67

I recommend striving to support multiple `evm` explorer clients, as well as BSC, Heco, etc. Rus

What's the purpose of this function?

https://github.com/Graviton-One/graviton-treasury/blob/6f12179d23c861d68495b896d6cf7f2fde720b4d/gravity_extractor/etherium_lu/src/lib.rs#L65

**Comment by BadConfig** [comment]
The next step is to add multiple evm chain support, so, i will make it by publishing a crate of ether scanner lib in rust
