### ISSUE TITLE
[Ethereum LU] Concurrency issue

### ISSUE THREAD

**Issue by sham789** [Graviton-One/graviton-treasury#5]
I see the instantiation of "mpsc" channel `(std lib)` for concurrency purposes.
We want multiple producers and a single consumer.

https://github.com/Graviton-One/graviton-treasury/blob/6f12179d23c861d68495b896d6cf7f2fde720b4d/gravity_extractor/etherium_lu/src/lib.rs#L139

And then, we call `tokio::spawn` where there's no multithreading, and we spawn `Future` here

https://github.com/Graviton-One/graviton-treasury/blob/6f12179d23c861d68495b896d6cf7f2fde720b4d/gravity_extractor/etherium_lu/src/lib.rs#L150

As mentioned here:

[tokio::spawn](https://docs.rs/tokio/0.1.22/tokio/runtime/struct.TaskExecutor.html#method.spawn)

Having a loop inside a future spawn closure is irrelevant. Consider spawning multiple lightweight futures either.

https://github.com/Graviton-One/graviton-treasury/blob/6f12179d23c861d68495b896d6cf7f2fde720b4d/gravity_extractor/etherium_lu/src/lib.rs#L145-L160

Moreover, does it work as expected?

**Comment by BadConfig** [comment]
I should propose test how it works, but still, tokio::tasks::spawn is asynchronous by default https://docs.rs/tokio/0.2.4/tokio/task/fn.spawn.html. Loop inside is required to properly count threads being spawned, we can span as many threads as we have data in the channel, for one thread to proc one data, may it be better?

**Comment by BadConfig** [comment]
issue completed in last commit into develop
